### ISSUE TITLE
Ansi colour codes emitted on Powershell

### ISSUE THREAD

**Issue by Michael-F-Bryan** [colin-kiegel/rust-pretty-assertions#15]
I've just reinstalled my work computer and it looks like `pretty_assertions` is now printing ansi codes instead of using the native windows mechanism for terminal colours. It's probably something to do with my environment, but do you have any idea why this may be happening even though cargo is able to print colours just fine?

Here's a screenshot to show the output.

![image](https://user-images.githubusercontent.com/17380079/32205281-5abaf3a8-be29-11e7-8efe-8731877ed7cd.png)

cc: #1

**Comment by colin-kiegel** [comment]
@Michael-F-Bryan: Thx for the report

- Did it work before for you?
- Does it work with older versions of `pretty_assertions`?

**Comment by Michael-F-Bryan** [comment]
Yeah, I used to use it all the time at work although I've had my `Cargo.toml` set to use `0.4` for a month or so now. I just tried version `0.3.4` and powershell is still printing the escape codes, meaning it's probably something to do with my environment and not your library. This is on a clean install of Windows 10 though, so I'm not 100% sure what the difference could be.

**Comment by Michael-F-Bryan** [comment]
@colin-kiegel, what are your thoughts on swapping to the [term] crate for rendering colours instead of `ansi_term`? For some reason PowerShell has decided it doesn't want to interpret ANSI escape codes again. I can always hack around this on my side, but it seems like a better solution in the long term would be to use a cross-platform terminal library.

[term]: https://crates.io/crates/term

**Comment by colin-kiegel** [comment]
@Michael-F-Bryan Sounds like a good idea to me. Feel free to send me a PR, if you want to. ;-)

**Comment by colin-kiegel** [comment]
this should be fixed by #28 now.

**Comment by Mingun** [comment]
Unfortunately, this still an issue on some machines. I have the some problem as topicstarter -- cargo output is colored, but `pretty_assertions` outputs ANSI codes instead. This happens only in VSCode integrated terminal (using PowerShell 7.2.0) and only on Windows 7 (Windows 10 and Windows 11 are fine). When I run tests in PowerShell console, output is colored as expected:
![The same output in VSCode and PowerShell in ConEmu](https://user-images.githubusercontent.com/450131/168858202-bbae9bef-f503-4102-8dd4-c3c4f5da9813.png)
Any thoughts, how to fix that?
